### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [BTNGaming/rrp_bodybag#1]
Problem in server/main.lua

**Comment by deviljin112** [comment]
see this [link](https://forum.fivem.net/t/release-esx-standalone-bodybag-for-pd-ems/873395/20?u=deviljin112)

**Comment by BTNGaming** [comment]
Have tried to replicate this several times. Have not found the issue anywhere. Please check your server again. 

The server file is 4 lines and I've had it working flawlessly for days. We have had multiple users test and confirm that this is an error on your end.

Good luck sir.
